---
title       : Retail Inventory Allocation Optimizer
subtitle    : A tool that determines the profit-optimal inventory level for a seasonal item
author      : David Leonard
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax, quiz, bootstrap]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---
<style>
.title-slide {
  background-color: #FFFFFF; /* #EDE0CF; ; #CA9F9D*/
}
</style>

## Allocating seasonal retail goods to stores is a balancing act

- Seasonal retail products have a short life and generally a limited supply (think fashion apparel, for example)
- Goods are acquired prior to the start of the season, and held at a Distribution Center (DC)
- In-season, units are allocated out of the DC to stores on an as-needed basis
- How do we decide how many units to send to each store in each allocation cycle?
    - If we stock too many, we could end up with "stranded" inventory at the end of the season; if we can't return those to the vendor, then we take a loss on the cost of each stranded unit.
    - If we stock too few, we will lose out on sales during the next "coverage period"
    - The challenge: *find the level of inventory that balances those two risks*

--- .class #id 

## We can use probability theory to estimate the total costs at different stocking levels

- A gamma distribution is typically used to describe retail consumer demand
- Given the demand rate and variability of demand, we can determine the probability of selling a given number of units over a specified period of time
- For allocation, we are concerned with two time periods:
    - The next coverage period (time between arrival of shipments plus the transit time of an order from the DC to the store), and
    - The time remaining in the season
- The total cost associated with a stocking level *s* is the sum of:
    - Lost margin = pr(Coverage Period Demand > *s*) x (Unit Margin)
    - Obsolescence cost = pr(Remaining Season Demand < *s*) x (Unit Cost) x (Obsolescence %)
- Compute cost for each stocking level below cumulative probability <99.9%, then find the level with the lowest total cost

--- .class #id 

## The Optimizer Finds the Most Profitable Inventory Level Based On Input Parameters

### Example: Daily Demand = 1 unit, Coverage Period = 9 days, Remaining Season = 4 wks, Variability = 40%, Margin = 50%

```{r echo = FALSE, fig.width = 14, fig.height = 6}
        # Create input list 
        input <- list(Margin = 50, DailyDemand = 1, Variability = 40,
                      SeasWks = 4,
                      CPRP = 7,
                      CPLT = 2)
        
        itemPrice <- 10
        
        # Get the input values into variables
        itemMargin <- input$Margin/100
        dailyDemand <- input$DailyDemand
        variability <- input$Variability/100
        seaswks <- input$SeasWks
        cpdays <- input$CPRP + input$CPLT

         # Now calculate all of the parameters we need for the gamma distribution functions
        
        itemCost <- (1 - itemMargin)*itemPrice
        cpdemand <- dailyDemand * cpdays
        seasdemand <- dailyDemand * seaswks * 7
        cpstdev <- variability * cpdemand
        seasstdev <- variability * seasdemand
        cpvar <- cpstdev^2
        seasvar <- seasstdev^2
        alpha <- (cpdemand/cpstdev)^2 # alpha is the same for both cp and season
        betaCP <- cpvar/cpdemand
        betaSeas <- seasvar/seasdemand
        
        segmentsperunit <- 10
        units <- seq(from = 0, to = seasdemand, by = 1/segmentsperunit)
        CPPDF <- dgamma(units, shape = alpha, scale = betaCP)
        CPCDF <- pgamma(units, shape = alpha, scale = betaCP)
        CPCDFp1 <- pgamma(units, shape = alpha+1, scale = betaCP)
        SeasPDF <- dgamma(units, shape = alpha, scale = betaSeas)
        SeasCDF <- pgamma(units, shape = alpha, scale = betaSeas)
        SeasCDFp1 <- pgamma(units, shape = alpha+1, scale = betaSeas)
        
        # Calculate the costs
        LSUnits <- cpdemand*(1-CPCDFp1) - units*(1-CPCDF)
        LSCost <- LSUnits*(itemMargin*itemPrice)
        
        obsUnits <- units*SeasCDF - seasdemand*SeasCDFp1
        obsCost <- obsUnits*itemCost
        
        TotCost <- LSCost + obsCost
        
        minCost <- min(TotCost)

        OptInvLevel <- round(units[TotCost == minCost],0)

# Generate a plot showing the PDFs for the two time periods, and the optimal inventory level
    linewidth = 4
    
    x <- units
    yCP <- CPPDF
    ySeas <- SeasPDF
    optInv <- OptInvLevel

    transval <- 0.333
    aucCPCol <- "maroon"
    aucSeasCol <- "blue3"

    aucCPRGB <- col2rgb(aucCPCol)/255
    aucSeasRGB <- col2rgb(aucSeasCol)/255
    aucCPColor <- rgb(aucCPRGB[1],aucCPRGB[2],aucCPRGB[3], transval)
    aucSeasColor <- rgb(aucSeasRGB[1],aucSeasRGB[2],aucSeasRGB[3], transval)
    chartcols <- c("maroon","blue3","black", aucCPColor, aucSeasColor)
    
    
    plot(x=x, y=yCP, type = "l", col = chartcols[1], lwd = linewidth,
         xlab = "Demand (Units)",
         ylab = "Probability",
         main = "Demand Probability For Next Coverage Period and Remainder of Season",
         cex.main = 1.5,
         cex.axis = 1.25,
         cex.lab = 1.5,
         bty = "n")
    lines(x=x, y=ySeas, type = "l", col = chartcols[2], lwd = linewidth)
    abline(v=optInv, col = chartcols[3], lwd = linewidth, lty = 3)
    polygon(c( x[x>=optInv], optInv ),  c(yCP[x>=optInv],0 ), col = aucCPColor)
    polygon(c( x[x<=optInv], optInv), c(ySeas[x<=optInv],0), col = aucSeasColor)
    text(x=optInv, 
         y = max(yCP)*.5, 
         cex =1.5,
         labels = paste("You should stock\n",
                        formatC(as.integer(optInv), digits = 0),
                        "units"),
         pos = 4)
    legend("topright", c("Next Coverage Period",
                         "Remainder of Season",
                         "Optimal Inventory Level",
                         "Probability of Lost Sales",
                         "Probability of Stranded Units"),
           col = chartcols,
           cex=1.25,
           lty = c(1,1,3,NA,NA), lwd = linewidth, bty = "n")
    
    legend("topright", c("Next Coverage Period",
                         "Remainder of Season",
                         "Optimal Inventory Level",
                         "Probability of Lost Sales",
                         "Probability of Stranded Units"),
           col = chartcols,
           cex=1.25,
           pch = c(NA, NA, NA, 15, 15), pt.cex = 3, bty = "n")

```

--- .class #id 

## The Inventory Optimizer Is Available For Evaluation

- You can try it [here](https://leonardanalytics.shinyapps.io/seasonalinventoryoptimizer/)
- Go to the Help tab for definitions of the inputs and other notes
- Use the sliders to adjust input parameters and observe the effect on the optimal inventory level
- Ideas for future enhancements:
    - Support additional inputs, such as 
        - coverage period and remainder of season average daily demand
        - Item price or cost
        - Obsolescence cost (as % of item cost) - currently it assumes 100%
    - Integrate with forecasting system to directly access demand predictions and measure of variance



